version: '2'

services:
  reverse-proxy:
    image: reverse-proxy
    ports:
        - 80:80
    restart: always

  coffee-challenge:
    depends_on:
        - reverse-proxy
    image: coffee-challenge
    ports:
        - "3000:3000"
    volumes:
        - ../coffee-challenge:/usr/src/app
    restart: always